#! /bin/sh

# autostart
sxhkd &
feh --bg-fill --randomize ~/Pictures/wallpaper &
xset r rate 200 50
xss-lock gnome-screensaver-command -l &
unclutter &
setxkbmap -option ctrl:nocaps &
launchLemon &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config presel_feedback_color "#6272a4"

bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"

